# Generated by Django 4.2.2 on 2023-06-11 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('air_date', models.DateField()),
                ('overview', models.TextField(blank=True, null=True)),
                ('runtime', models.IntegerField()),
                ('still_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enchiridionapi.episode')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enchiridionapi.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='episodes',
            field=models.ManyToManyField(related_name='playlists', through='enchiridionapi.PlaylistEpisode', to='enchiridionapi.episode'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
