# Generated by Django 4.2.2 on 2023-06-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enchiridionapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='series_name',
            field=models.CharField(default='Adventure Time', max_length=100),
            preserve_default=False,
        ),
    ]
